/*
 Generated by typeshare 1.13.4
*/

export interface ControllerInputPayload {
	thrust: boolean;
	rotate_left: boolean;
	rotate_right: boolean;
	fire: boolean;
}

export interface ErrorPayload {
	code: number;
	message: string;
}

export interface GameStartedPayload {
	game_type: string;
}

export interface JoinSessionPayload {
	session_code: string;
	nickname: string;
}

export interface JoinSuccessPayload {
	player_id: string;
	session_code: string;
}

export interface PingPayload {
	message: string;
}

export interface PlayerInfo {
	player_id: string;
	nickname: string;
}

export interface PlayerInputPayload {
	player_id: string;
	thrust: boolean;
	rotate_left: boolean;
	rotate_right: boolean;
	fire: boolean;
}

export interface PlayerJoinedPayload {
	player_id: string;
	nickname: string;
}

export interface PlayerLeftPayload {
	player_id: string;
}

export interface PongPayload {
	message: string;
}

export interface SessionCreatedPayload {
	session_code: string;
}

export interface StartGamePayload {
	game_type: string;
}

export type ControllerEvent = 
	| { status: "success", data: ControllerEventType }
	| { status: "error", data: ErrorPayload };

export type ControllerEventType = 
	| { type: "ping", payload: PingPayload }
	| { type: "joinSession", payload: JoinSessionPayload }
	| { type: "playerInput", payload: ControllerInputPayload };

export type HostEvent = 
	| { status: "success", data: HostEventType }
	| { status: "error", data: ErrorPayload };

export type HostEventType = 
	| { type: "ping", payload: PingPayload }
	| { type: "createSession", payload?: undefined }
	| { type: "startGame", payload: StartGamePayload }
	| { type: "gameStarted", payload: GameStartedPayload };

export type ServerToControllerEvent = 
	| { status: "success", data: ServerToControllerEventType }
	| { status: "error", data: ErrorPayload };

export type ServerToControllerEventType = 
	| { type: "pong", payload: PongPayload }
	| { type: "joinSuccess", payload: JoinSuccessPayload }
	| { type: "gameStarted", payload: GameStartedPayload };

export type ServerToHostEvent = 
	| { status: "success", data: ServerToHostEventType }
	| { status: "error", data: ErrorPayload };

export type ServerToHostEventType = 
	| { type: "pong", payload: PongPayload }
	| { type: "sessionCreated", payload: SessionCreatedPayload }
	| { type: "playerJoined", payload: PlayerJoinedPayload }
	| { type: "playerLeft", payload: PlayerLeftPayload }
	| { type: "playerInput", payload: PlayerInputPayload };

