/*
 Generated by typeshare 1.13.4
*/

export interface ControllerInputPayload {
	player_id: string;
	input_type: string;
	data: string;
}

export interface CreateSessionPayload {
}

export interface ErrorPayload {
	code: number;
	message: string;
}

export interface GameStartedPayload {
	game_type: string;
}

export interface JoinSessionPayload {
	session_code: string;
	player_name: string;
}

export interface JoinSuccessPayload {
	player_id: string;
	session_code: string;
}

export interface PingPayload {
	message: string;
}

export interface PlayerInfo {
	player_id: string;
	player_name: string;
}

export interface PlayerInputPayload {
	input_type: string;
	data: string;
}

export interface PlayerJoinedPayload {
	player: PlayerInfo;
}

export interface PlayerLeftPayload {
	player_id: string;
}

export interface PongPayload {
	message: string;
}

export interface SessionCreatedPayload {
	session_code: string;
}

export interface StartGamePayload {
}

export type ControllerEvent = 
	| { status: "success", data: ControllerEventType }
	| { status: "error", data: ErrorPayload };

export type ControllerEventType = 
	| { type: "ping", payload: PingPayload }
	| { type: "joinSession", payload: JoinSessionPayload }
	| { type: "playerInput", payload: PlayerInputPayload };

export type HostEvent = 
	| { status: "success", data: HostEventType }
	| { status: "error", data: ErrorPayload };

export type HostEventType = 
	| { type: "ping", payload: PingPayload }
	| { type: "createSession", payload: CreateSessionPayload }
	| { type: "startGame", payload: StartGamePayload };

export type ServerToControllerEvent = 
	| { status: "success", data: ServerToControllerEventType }
	| { status: "error", data: ErrorPayload };

export type ServerToControllerEventType = 
	| { type: "pong", payload: PongPayload }
	| { type: "joinSuccess", payload: JoinSuccessPayload }
	| { type: "gameStarted", payload: GameStartedPayload };

export type ServerToHostEvent = 
	| { status: "success", data: ServerToHostEventType }
	| { status: "error", data: ErrorPayload };

export type ServerToHostEventType = 
	| { type: "pong", payload: PongPayload }
	| { type: "sessionCreated", payload: SessionCreatedPayload }
	| { type: "playerJoined", payload: PlayerJoinedPayload }
	| { type: "playerLeft", payload: PlayerLeftPayload }
	| { type: "controllerInput", payload: ControllerInputPayload };

