/*
 Generated by typeshare 1.13.4
*/

export interface PingMessage {
	msg: string;
}

export interface PongMessage {
	msg: string;
}

export type ControllerMessage = 
	| { type: "Ping", content: PingMessage }
	| { type: "Pong", content: PongMessage };

